[package]
name = "nothing-ear-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bluer = { version = "0.17.3", features = ["full"] }
tokio = { version = "1", features = ["full"] }
bluetooth-serial-port = "0.6.0"
serialport = "4.6.0"
serde = "1.0.215"
serde_json = "1.0.133"
